---
- name: Ensure that the node_exporter user exists
  user:
    name: "node_exporter"
    shell: /bin/false
    state: present
- name: Copy node_exporter binary
  copy:
    src: "files/distrib/node_exporter"
    dest: "/usr/bin/node_exporter"
    mode: 0755
- name: Copy systemd service file
  template:
    src: "node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"
  register: node_exporter_service
- name: Reload systemd if service file is changed
  systemd:
    daemon_reload: true
  notify: restart_node_exporter
  when: node_exporter_service is changed
- name: Ensure node_exporter is started
  ansible.builtin.systemd:
    name: node_exporter.service
    enabled: yes
    state: started
- name: enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: reloaded
- name: Open port 9100 in firewall
  ansible.builtin.firewalld:
    port: 9100/tcp
    permanent: yes
    immediate: yes
    state: enabled
