---
- name: Ensure that the prometheus user exists
  user:
    name: "prometheus"
    shell: /bin/false
- name: Copy prometheus binary
  copy:
    src: "files/distrib/prometheus"
    dest: "/usr/bin/prometheus"
    mode: 0755
- name: Copy systemd service file
  template:
    src: "prometheus.service.j2"
    dest: "/etc/systemd/system/prometheus.service"
- name: Ensure prometheus folder exists in etc
  file:
    state: directory
    path: /etc/prometheus
    owner: "prometheus"
    group: "prometheus"
    mode: 0755
- name: Copy prometheus config from template
  template:
    src: "prometheus.yml.j2"
    dest: "/etc/prometheus/prometheus.yml"
- name: create /var/lib/prom—Étheus/data
  file:
    state: directory
    path: /var/lib/prometheus/data
    recurse: true
    owner: "prometheus"
    group: "prometheus"
    mode: 0755
- name: Systemd reload to pickup new service
  systemd:
    daemon-reload: true
    enabled: true
    state: restarted
    name: "prometheus.service"
  notify: restart_prometheus_server
- name: Open port 9090 in firewall
  ansible.builtin.firewalld:
    port: 9090/tcp
    permanent: yes
    immediate: yes
    state: enabled
